package com.example.demo.controllers;

import com.example.demo.models.Capital;
import com.example.demo.models.Country;
import com.example.demo.repositories.CapitalRepository;
import com.example.demo.repositories.CountryRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

public class CountryController {


    @Controller                            // This means that this class is a Controller
    @RequestMapping(path = "/country")               // This means URL's start with /demo (after Application path)
    public class MainController {
        // This means to get the bean called bookRepository
        @Autowired
        // Which is auto-generated by Spring, we will use it to handle the data
        private CountryRepository countryRepository;

        @GetMapping(path = "/add")
        public @ResponseBody
        String addNewUser(@RequestParam String name) {
            // @ResponseBody means the returned String is the response, not a view name
            // @RequestParam means it is a parameter from the GET or POST request

            Country n = new Country();
            n.setName(name);
            //TODO capital
            countryRepository.save(n);
            return name + "is Saved";
        }

        @GetMapping(path="/all")
        public @ResponseBody Iterable<Country> getAllCountries() {
            // This returns a JSON or XML with the users
            return countryRepository.findAll();
        }

    }

}
