package com.example.demo.controllers;


import com.example.demo.models.Capital;
import com.example.demo.repositories.CapitalRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;


@RestController
    @RequestMapping(path = "/")
    public class MainController {

    @Autowired
    // Which is auto-generated by Spring, we will use it to handle the data
    private CapitalRepository capitalRepository;

        @GetMapping(path = "/")
        public String index() {

            return "Welcome";
        }


    @GetMapping(path = "/add")
    public String addNewUser(@RequestParam String name) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Capital n = new Capital();
        n.setName(name);
        capitalRepository.save(n);
        return name + "is Saved";
    }

    @GetMapping(path="/all")
    public Iterable<Capital> getAllCapitals() {
        // This returns a JSON or XML with the users
        return capitalRepository.findAll();
    }



}


